spring:
  datasource:
    url: jdbc:mysql://192.168.5.5:3307/SpringBoot-stu
    username: root
    password: acane
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # 更新表，若无表则创建
    show-sql: true # 显示SQL语句