spring:
  profiles:
    active: dev

# 字面量
name: aca
speech:
  1: 'Hello \n World' # 使用单引号忽略转义
  2: "Hello \n World" # 使用双引号识别转义，表示普通的字符串

#map、对象
person:
  name: ${name}
  age: 18
  speech: ${speech.1}

# 数组
list:
  - baidu.com
  - youtube.com
  - x.com

